version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_go
    environment:
      POSTGRES_USER: user_projeto
      POSTGRES_PASSWORD: password_projeto
      POSTGRES_DB: db_estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data:
